---



- hosts: all
  become: yes
  remote_user: ansible
  tasks:


  - name: update repo index
    apt:
      name: 
        - "{{my_package}}" 
      state: latest
      update_cache: yes
    when: ansible_distribution in ["Ubuntu"]


  
  - name: update repo index in centos
    yum:
      update_cache: yes
    when: ansible_distribution in ["CentOS"]



  - name: install snapd package yam latest version
    yum:
      name: 
        - "{{my_package}}"
      state: latest
    when: ansible_distribution in ["CentOS" ]
