---


- hosts: all
  tasks:

          - name: Shutdown server
            become: yes
            shell: sleep 2 && /sbin/shutdown -c && /sbin/shutdown -h now
            async: 1
            poll: 0

