---



- hosts: all
  become: true
  tasks:


  - name: update repo index
    apt:
      update_cache: yes
    when: ansible_distribution in ["Ubuntu" , "Linux Mint"]


     
  - name: install snapd package latest version
    apt:
      name: snapd
      state: latest
    when: ansible_distribution in ["Ubuntu" , "Linux Mint"]
